### ISSUE TITLE
解析附件中的表格会报错

### ISSUE THREAD

**Issue by chenyulzhh** [zavier/ReadWordTable#1]
[table1.docx](https://github.com/zavier/ReadWordTable/files/1562119/table1.docx)

会在 getRowspan 里面爆空指针异常
可能原因大概是在第83行，递归调用getRowspan 方法时，传入的 col 可能已经比 当前行的列数 colsNum 大了，
我反正被代码逻辑绕晕了，
瞎改成 getRowspan(table, row, Math.min(col, colsNum-1), list); 
这种方式调用，不会报错，转换出来html    似乎   也是对的。。

**Comment by zavier** [comment]
多谢！已修复
